const jobs = [
    'Administrative Assistant',
    'Assistant Coach',
    'Assistant Librarian',
    'Behavior Specialist',
    'Bus Driver',
    'Carpenter',
    'Coach',
    'Communication Specialist',
    'Computer Technician',
    'Counselor',
    'Curriculum Developer',
    'Food Service Assistant',
    'Food Service Worker',
    'Gardener',
    'Groundskeeper',
    'Human Resources Director',
    'Janitor',
    'Librarian',
    'Maintainance Technician',
    'Nurse',
    'Nutritionist',
    'Occupational Therapist',
    'Physical Therapist',
    'Psychologist',
    'Reading Specialist',
    'Registrar',
    'Security Guard',
    'Speech Therapist',
    'Teacher',
    'Webmaster'
]

export default jobs;